### ISSUE TITLE
GraphAPICaller.m mentioned in the instructions, but isn't in project

### ISSUE THREAD

**Issue by jcabreram** [AzureADQuickStarts/NativeClient-iOS#1]
Hi! I can't seem to find the GraphAPICaller.m file that is mentioned in the README in the Xcode project or the GitHub repo. Can you help me updating the instructions please?

**Comment by KeIMG** [comment]
Hi! I can't find the GraphAPICaller.m file either

**Comment by jmprieur** [comment]
Closing as this sample is now archived. 
See new sample
