### ISSUE TITLE
Unable to Authenticate Azure ADAL iOS Swift Library to access Azure Mobile Apps Easy Tables Data

### ISSUE THREAD

**Issue by kkadapa** [AzureADQuickStarts/NativeClient-iOS#8]
I am terribly in need of help reg Azure AD, i enabled AD for a mobile app in Azure and went to app registrations and added "add a reply URL as msal<AppId>://auth", and using this swift [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-objc/tree/dev/Samples/ios/SampleAppiOS-Swift) code to do AD Auth... Should i use [AzureAD](https://github.com/AzureADQuickStarts/NativeClient-iOS) or MSAL for our Organization only AD Auth?

I followed the docs meticulously added this in my Native App Reg :**urn:ietf:wg:oauth:2.0:oob** I am trying the below and my AD is not working :( i get the following exception
**Thread 2: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)** near `self.client.login(withProvider:"aad"` i know this is an Xcode error but 
, @brandwe the swift code in this page [[(Azure ios AD)](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal)] is old and documentation is poor. Can i get help?

```
authContext?.acquireToken(withResource: resourceId, clientId: clientId, redirectUri: (redirectUri! as URL), completionBlock: { (result) in    
if result!.status != AD_SUCCEEDED {
                completion(nil, result!.error)
            }
            else {
                print("access TOKEN IS ",result?.tokenCacheItem.accessToken as Any)
                let payload: [String: String] = ["access_token": (result?.tokenCacheItem.accessToken)!]
                //client.loginWithProvider("aad", token: payload, completion: completion)
                self.client.login(withProvider: "aad", token: payload, completion:(completion as! MSClientLoginBlock))
            }
        })
```

**EDIT**: I got the access token and when does the token expire? how often should i refresh the token?

var expiresOnString = "(nil)"

                if let expiresOn = result!.tokenCacheItem.expiresOn {
                    expiresOnString = String(describing: expiresOn)
                }

                let status = String(format: "Access token: %@\nexpiration:%@", result!.accessToken, expiresOnString)
                self.updateLogging(text:status)
the above code gives me 18:37:41 +0000 which means the access-token expires in one hour, how do i refresh this and make sure the App talks to DB? 

Is there an existing SampleApp (AAD talking to Mobile App Easy Tables) that i can refer to ?

**Second Edit**
I followed this article and trying to do refresh token but wondering if this works even for AAD to talk to the DB according to [Azure Docs] (https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal)

https://stackoverflow.com/questions/44168741/ios-adal-make-silent-call-using-refresh-token/44170226#44170226

**Comment by jmprieur** [comment]
Closing as this sample is now archived. 
See new sample
